name: mryao
on: push
jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - run: cd templates/frontend && npm i
      - run: cd templates/frontend && npm run dev &
      - run: pip3 install flask flask_cors pymongo
      - run: python3 index.py &
      - run: ret=$(curl -i http://localhost:8080/#/ | grep "200 OK") [ -z "$ret2" ];echo $?
